### ISSUE TITLE
can not run Aodvvanet scenario

### ISSUE THREAD

**Issue by nedabagheri** [jlsirois/VANETProject#1]
sloved

Hi dear joanne
I am trying to run aodv routing for erlangen scenario in veins. I imported your code and inetmanet 2.2 branch inetmanet 2.0 .
it does not work.it compiles and everything looks ok , but it does not make the exe file and says that the exe file is missing. am I doing sth wrong? do you have any idea where it might be wrong? :(

this is solved now, the omnet++ GUI didn't make the files correct, I used the command line and $opp_makemake -f, and then $make, and its ok now.

**Comment by chaotictoejam** [comment]
I will investigate this tonight. All scenarios should run except AODVVANET2
which is under development. Be sure to have my version of inetmanet and
have vanetsim reference it. Build inetmanet first before building vanetsim.
The exe file should generate from the build.

**Comment by nedabagheri** [comment]
![error](https://cloud.githubusercontent.com/assets/13317785/8654375/1886fb24-299f-11e5-9ecb-b8fb0c1e701f.JPG)

**Comment by nedabagheri** [comment]
Hi dear joanne, do you have good news?
I made a new work space and tried to import/compile the inetmanet . I got this warrning befor ebut didn't pay attention:

![another error](https://cloud.githubusercontent.com/assets/13317785/8665981/ae12942c-29ff-11e5-9d30-6019b2da7c41.JPG)

I imported vanetSim and compiled it right befor beginning to compile it gave me this warning:
![error 2](https://cloud.githubusercontent.com/assets/13317785/8666217/5c5b87de-2a03-11e5-9ae8-6b93449483bf.JPG)

actually these are not new cause these happened the first time I sent you the msg but I had no other choice to just go with it. and maybe these are not important.
best wishes

**Comment by nedabagheri** [comment]
sumo is listening, the scenario is beginning to launch but it crashes.
I have the original veins code and it works perfectly with sumo , the daemon has no problem.
![traciscenariomanagerlaunched](https://cloud.githubusercontent.com/assets/13317785/8666775/2c5f7c04-2a0b-11e5-8fd2-1a5cd1a12e2f.JPG)
