### ISSUE TITLE
TraciScenarioManagerLaunchd error

### ISSUE THREAD

**Issue by nedabagheri** [jlsirois/VANETProject#2]
the Traciscenariomanagerlaunchd crashes, right after the sumo in listening on port 9999.

![traciscenariomanagerlaunched](https://cloud.githubusercontent.com/assets/13317785/8667901/a4c8c2fe-2a1a-11e5-8102-1a9f3f60793a.JPG)

**Comment by chaotictoejam** [comment]
I pulled all code down to a new instance, and I could not get this error...

Which version of SUMO do you have? Can you check the SUMO instance for the detailed error.

**Comment by nedabagheri** [comment]
it was all because of this line: 

![error](https://cloud.githubusercontent.com/assets/13317785/8675827/3993a22e-2a5b-11e5-828a-c93f79730989.JPG)

thank you dear joanne

**Comment by chaotictoejam** [comment]
Ah, yes I will need to add that to the readme to change.
