### ISSUE TITLE
car accident

### ISSUE THREAD

**Issue by nedabagheri** [jlsirois/VANETProject#3]
Hi dear joanne

how can I make the vanetaodv scenario have car accidents like the veins example?
I imported the erlangen scenario cause I want to work on it and the cars are generating fine but they keep going they are not doing msg passing.

I earased the # sign before these three lines:

_.vehicle[_0].mobility.accidentCount = 1
_.vehicle[_0].mobility.accidentStart = 75s
_.vehicle[_0].mobility.accidentDuration = 30s

but yet there is no scheduled accident msg comig up...

**Comment by chaotictoejam** [comment]
These are not completed projects. This is my PhD research and therefore is under development. 

Uncommenting the code should enable the accident to run. You can see the accident happening on the top of the gui. AODVVANET and all VANET specific protocols are currently under dev. If you look at AODV, AODVUU, DSR, OLSR you can see some examples. GPSR fails in some cases. 

If you are using this for your research please be sure to site this repository. I am in the process of publishing a paper, but before it is finished please use:

Skiles, Joanne, VANET Project, GitHub Repository, https://github.com/jlsirois/VANETProject (2015) 

(Or whatever citation style you have)

BibTex
@misc{Skiles2015,
  author = {Joanne Skiles,},
  title = {VANET  Project},
  year = {2015},
  publisher = {GitHub},
  journal = {GitHub repository},
  howpublished = {\url{https://github.com/jlsirois/VANETProject}},
  commit = {comment#}
}

**Comment by nedabagheri** [comment]
sure my dear I will cite this repository

my first step is to get an outcome from aodvvanet( having the accidents and packetlost plot). I'm doing this part for my master thesis and I'm reaching my deadline. if I make this code work in 4 days, I'm safe otherwise i'm screwed. it goes to the next semester and...

sorry that I'm causing you trouble

**Comment by chaotictoejam** [comment]
Its not a problem. I have unfortunately have had the same experience and
know what you are going through.

Look at AODV, AODVUU, DSR, or OLSR simulations and enable the accident
code. These are all the base MANET protocols, which I am assuming you want
to compare on performance?

I am currently at work. But when I get home I will see if I can see why the
message is not being sent for AODVVANET.

**Comment by nedabagheri** [comment]
Hi Joanne
did you find anything?

**Comment by chaotictoejam** [comment]
I check in some changes AODV, AODVUU, DSR, and OLSR have Erlangen with the
accident set up in the ini. Be sure to update the erlangen.launchd.xml file
locations.
