### ISSUE TITLE
Help in building

### ISSUE THREAD

**Issue by the-elves** [jlsirois/VANETProject#4]
Dear jlsirois,
I was able to run your code but after a lot of changes in source, which i am sure were not required. and it was my mistake in building the project, caused following issues.
When I downloaded the project and your version of inetmanet and imported it in omnetpp eclipse ide.
I could not get to run it. 
1)It fired the error The aodvTraCIScenarioManagerLaunchd not found. Perhaps the module is not registered. ...
When I edited in the aodvTraCIScenarioManagerLaunchd.cc, then reverted it back to original and built again, The project launched. 
2)After selecting aodvvanet config, it did not load its configurations by default. and we had to enter them manually picking them from omnetpp.ini of aodvvanet folder from simulations folder.
3) manetrouting module of AODVVANETCar.ned sent probe request to every node on the scenario, whether they were in range or not. The positions of all the radios were not changing on signal, hence all the radios were at same position, therefore computing distance between them as 0. 
4) I could not run individual omnetpp.ini from aodvvanet folder of simulations folder.
5) When i built from eclipse, it didn't build the project and fired a error, "This is not a eclipse CDT project", i had to manually build it using make from command line.

I say again, I know the project is working fine,More than that, the code is elegant(I have been through almost all of it while trying to get it to run). I made some mistake while building it, importing it or some where else. 
Please tell me where am I going wrong. These are the steps I followed. 
1) I downloaded inetmanet from your repo
2) I downloaded VANETProject from your repo
3) Unzipped both of them in respective folders
4) Imported both the projects in omnet eclipse IDE 
5) Gave references as required and set the ned folders as required
6) Built
Any help appreciated. 
Thanks for your valuable time.
You could reply me at kyaajin@gmail.com
PS. i follow your blog :)

**Comment by chaotictoejam** [comment]
I pulled from github the code onto my laptop (fresh load)  and I was able to get it to build. 
I did notice that if the project is pulled from a zip the excluded folders do not seem to be excluded from the build. Excluded files should be src/routing/gpsr and srcs/veins.

Although this shouldn't make a difference which version of omnet++ are you using?

AODVVANET is based off of a paper I was given, and is currently under development, but I do know the modules it references are registered...,to further extend on that all custom routing protocols are under development for my research and change frequently. If you want to use AODV in a VANET simulation use AODVUU or AODV. 

But nice to know I somehow messed up the radios in one of my updates I will fix that tonight.

**Comment by the-elves** [comment]
just to make some debugging easy for u, the signals subscribe by radios and
emited by mobility are different
also the mobility inside manet routing is not updated by
aodvtraciscenariomangagerlaunchd.
i am using omnet 4.4 with sumo 0.19.0,

Ajinkya Rajput
Chairperson
PICT IEEE Student Branch
