### ISSUE TITLE
Help with RBVT

### ISSUE THREAD

**Issue by Cyberian87** [jlsirois/VANETProject#5]
Hello,
I doing this research on VANET routing protocols specifically RBVT.
I come across your code which I must say is very diverse.
I need help with RBVT, right now I'm not really sure how to run the RBVT.
I am new to OMNET++. I apologize for for such a silly question.
Can you tell me how can I run a scenario with RBVT.
I have done the following steps.
1) Download vanetproject
2) Download inetmanet from your repository
3) Unzipped both in respective folders and then imported in OMNET++.
4) I'm also not sure about the referencing because when I put inetmanet in reference in VANETsim I get so many errors of same type such as 'ARP': no such module type. Can you also give me a hint for that.

Thanks
my emai: hassaanghazi@live.com

**Comment by chaotictoejam** [comment]
Sorry most of this code is offline now as it relates to my dissertation work
