### ISSUE TITLE
VANETProject importation problem 

### ISSUE THREAD

**Issue by mohamedbenbeziane** [jlsirois/VANETProject#8]
Hello Joanne,
First of all, I am sure you did a great job. 
I follow all steps that you mentioned,  i update my omnet++5.3 into omnet++ 5.4.1, veins 4.7.1, your inet that you made modifications and sumo 0.29. when, i build them they work very well without errors but when i import your project i couldn't build it ???? i want to use aodv protocol in my scenario vanet. I am preparing a scientific paper in vehicular cloud using routing protocol. i am looking forward to hearing your eventual response.
thanks.
![1](https://user-images.githubusercontent.com/50850444/78503810-d4dc6200-7760-11ea-8c41-bbb9cf4541b4.JPG)
![2](https://user-images.githubusercontent.com/50850444/78503813-db6ad980-7760-11ea-92c1-ac3228703398.JPG)

**Comment by mohamedbenbeziane** [comment]
hello, there is no srrors in building but in the simulation i have this jointed picture. plz help me 
![trafficlightmoduletype](https://user-images.githubusercontent.com/50850444/78580822-e68a3c00-782a-11ea-91ba-490bf94fc47a.JPG)

**Comment by chaotictoejam** [comment]
Hi, the repository has been updated. Please be sure to use veins 5.0 and the latest inet version.
